# Generated by Django 4.2.21 on 2025-10-29 05:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('room_number', models.CharField(default='', max_length=10)),
                ('hostel_type', models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default='B', max_length=1)),
                ('contact_number', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be 10 digits', regex='^\\d{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('hostel_type', models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], max_length=1)),
                ('student_name', models.CharField(default='', max_length=100)),
                ('student_id', models.CharField(default='', max_length=20)),
                ('contact_number', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be 10 digits', regex='^\\d{10}$')])),
                ('query_category', models.CharField(choices=[('maintenance', 'Maintenance Issue'), ('electrical', 'Electrical Problem'), ('plumbing', 'Plumbing Problem'), ('furniture', 'Furniture Issue'), ('cleanliness', 'Cleanliness Concern'), ('wifi', 'Internet/WiFi Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('query_text', models.TextField(default='')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('R', 'Resolved')], default='P', max_length=2)),
                ('expected_resolution_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
