# Generated by Django 4.2.21 on 2025-10-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0002_query_completed_by'),
    ]

    operations = [
    ]
